# Generated by Django 3.2.8 on 2024-02-25 15:06

import backend.expertdb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutpatientSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GP', '普通专家门诊'), ('SP', '高级专家门诊')], default='GP', max_length=2, verbose_name='门诊类别')),
                ('week', models.IntegerField(choices=[(0, '星期一'), (1, '星期二'), (2, '星期三'), (3, '星期四'), (4, '星期五'), (5, '星期六'), (6, '星期日')], verbose_name='班次')),
            ],
            options={
                'verbose_name': '门诊排班',
                'verbose_name_plural': '门诊排班',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='姓名')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=backend.expertdb.models.Doctor.user_directory_path, verbose_name='头像')),
                ('doctor_title', models.CharField(choices=[('AP', '主任医师'), ('AAP', '副主任医师'), ('CR', '主治医师')], default='AP', max_length=3, verbose_name='医务职称')),
                ('teacher_title', models.CharField(blank=True, choices=[('PR', '教授'), ('APR', '副教授')], default='PR', max_length=3, null=True, verbose_name='教学职称')),
                ('doctor_office', models.CharField(blank=True, max_length=20, null=True, verbose_name='医务职位')),
                ('teacher_office', models.CharField(blank=True, max_length=20, null=True, verbose_name='教学职位')),
                ('degree', models.CharField(choices=[('MB', '医学学士'), ('MM', '医学硕士'), ('MD', '医学博士')], default='MD', max_length=10, verbose_name='学历')),
                ('major', models.CharField(max_length=10, verbose_name='专业')),
                ('field', models.TextField(verbose_name='擅长领域')),
                ('info', models.TextField(verbose_name='介绍')),
                ('schedule', models.ManyToManyField(to='expertdb.OutpatientSchedule', verbose_name='门诊排班')),
            ],
            options={
                'verbose_name': '专家库',
                'verbose_name_plural': '专家库',
            },
        ),
    ]
