# Generated by Django 3.2.8 on 2024-02-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='link',
            field=models.URLField(blank=True, max_length=300, verbose_name='挂号网址'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(choices=[('MB', '医学学士'), ('MM', '医学硕士'), ('MD', '医学博士'), ('MPD', '医学博士后')], default='MD', max_length=10, verbose_name='学历'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='major',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='teacher_title',
            field=models.CharField(blank=True, choices=[('PR', '教授'), ('APR', '副教授')], max_length=3, null=True, verbose_name='教学职称'),
        ),
        migrations.AlterField(
            model_name='outpatientschedule',
            name='category',
            field=models.CharField(choices=[('GP', '普通专家门诊'), ('SP', '高级专家门诊'), ('IN', '互联网门诊')], default='GP', max_length=2, verbose_name='门诊类别'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='major',
            field=models.ManyToManyField(to='expertdb.Profession', verbose_name='专业'),
        ),
    ]
