# Generated by Django 3.2.8 on 2024-02-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='link',
            field=models.URLField(blank=True, verbose_name='挂号网址'),
        ),
    ]
