# Generated by Django 3.2.8 on 2024-02-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertdb', '0002_doctor_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
            },
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='major',
        ),
        migrations.AddField(
            model_name='doctor',
            name='major',
            field=models.ManyToManyField(to='expertdb.Profession', verbose_name='专业'),
        ),
    ]
