# Generated by Django 3.2.8 on 2024-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertdb', '0003_auto_20240310_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': '专业组', 'verbose_name_plural': '专业组'},
        ),
        migrations.AlterModelOptions(
            name='sectiondoctors',
            options={'verbose_name': '专业专家', 'verbose_name_plural': '专业专家'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(blank=True, choices=[('MB', '医学学士'), ('MM', '医学硕士'), ('MD', '医学博士'), ('MPD', '医学博士后')], max_length=10, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='teacher_office',
            field=models.CharField(blank=True, choices=[('MT', '硕导'), ('DT', '博导')], max_length=20, null=True, verbose_name='教学职位'),
        ),
    ]
