# Generated by Django 3.2.8 on 2024-02-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertdb', '0003_auto_20240228_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(choices=[('MB', '医学学士'), ('MM', '医学硕士'), ('MD', '医学博士'), ('MPD', '医学博士后')], default='MD', max_length=10, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='outpatientschedule',
            name='category',
            field=models.CharField(choices=[('GP', '普通专家门诊'), ('SP', '高级专家门诊'), ('IN', '互联网门诊')], default='GP', max_length=2, verbose_name='门诊类别'),
        ),
    ]
