# Generated by Django 3.2.8 on 2024-03-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expertdb', '0004_auto_20240229_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '专业组',
                'verbose_name_plural': '专业组',
            },
        ),
        migrations.CreateModel(
            name='SectionDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, null=True, verbose_name='介绍')),
            ],
            options={
                'verbose_name': '专业专家',
                'verbose_name_plural': '专业专家',
            },
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='field',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='info',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='major',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(blank=True, choices=[('MB', '医学学士'), ('MM', '医学硕士'), ('MD', '医学博士'), ('MPD', '医学博士后')], max_length=10, null=True, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='挂号网址'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='teacher_office',
            field=models.CharField(blank=True, choices=[('MT', '硕导'), ('DT', '博导')], max_length=20, null=True, verbose_name='教学职位'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='teacher_title',
            field=models.CharField(blank=True, choices=[('PR', '教授'), ('APR', '副教授')], max_length=3, null=True, verbose_name='教学职称'),
        ),
        migrations.DeleteModel(
            name='OutpatientSchedule',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.AddField(
            model_name='sectiondoctors',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertdb.doctor'),
        ),
        migrations.AddField(
            model_name='sectiondoctors',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertdb.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='doctors',
            field=models.ManyToManyField(blank=True, through='expertdb.SectionDoctors', to='expertdb.Doctor'),
        ),
    ]
