# Generated by Django 3.2.8 on 2024-03-13 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expertdb', '0005_auto_20240312_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='link',
        ),
        migrations.AddField(
            model_name='sectiondoctors',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='挂号网址'),
        ),
        migrations.AlterField(
            model_name='section',
            name='doctors',
            field=models.ManyToManyField(blank=True, through='expertdb.SectionDoctors', to='expertdb.Doctor', verbose_name='专家'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=20, verbose_name='专业组名称'),
        ),
        migrations.AlterField(
            model_name='sectiondoctors',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertdb.doctor', verbose_name='专家'),
        ),
        migrations.AlterField(
            model_name='sectiondoctors',
            name='info',
            field=models.TextField(verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='sectiondoctors',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertdb.section', verbose_name='专业组'),
        ),
    ]
