# Generated by Django 3.2.8 on 2024-03-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertdb', '0006_auto_20240313_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiondoctors',
            name='link',
        ),
        migrations.AddField(
            model_name='doctor',
            name='link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='挂号网址'),
        ),
    ]
